alias ll="ls -Glahs"
alias ls="/bin/ls -G"
alias psgrep="ps aux | egrep -v egrep | egrep"
alias edit="/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"
alias gka="gitk --all 2> /dev/null &"
alias gk="gitk 2> /dev/null &"
alias myintip="ifconfig en0 | grep 'inet ' | sed -e 's/^.*inet //g' | sed -e 's/ netmask.*//g'"
alias myextip="curl -s http://checkip.dyndns.org | sed 's/[a-zA-Z/<> :]//g'"